# Generated by Django 4.2.3 on 2023-07-25 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_task_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
