# Generated by Django 4.2.3 on 2023-07-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
