# Generated by Django 4.2.3 on 2023-07-26 15:46

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_task_duration_task_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=account.models.task_file_upload_to),
        ),
    ]
