# Generated by Django 4.2.3 on 2023-07-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_mytag_task_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
        migrations.AddField(
            model_name='mytag',
            name='tasks',
            field=models.ManyToManyField(related_name='tags', to='account.task'),
        ),
    ]
