# Generated by Django 4.2.3 on 2023-07-28 22:26

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('account', '0015_remove_mytag_tasks_tasktag_task_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tasktag',
            name='task',
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='MyTag',
        ),
        migrations.DeleteModel(
            name='TaskTag',
        ),
    ]
