# Generated by Django 4.2.3 on 2023-07-29 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_task_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
    ]
