# Generated by Django 4.2.3 on 2023-08-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_task_send_email_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
